# Generated by Django 5.1.2 on 2024-10-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_skills_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='skill',
            name='percentage',
            field=models.PositiveIntegerField(),
        ),
    ]
