# Generated by Django 5.1.2 on 2024-11-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_list_category_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='list_category',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
